name    'stiron-go-mtpfs'
version '0.1.2'
source 'https://github.com/stiron/stiron-go-mtpfs'
author 'Tamas MOLNAR'
license 'Apache License, Version 2.0'
summary 'This module installs the go-mtpfs package on Ubuntu'
description 'This module installs the go-mtpfs package on Ubuntu to mount Android devices with it'
project_page 'https://github.com/stiron/stiron-go-mtpfs'

dependency 'puppetlabs/apt', '>= 1.4.1'
